# Generated by Django 4.2.23 on 2025-09-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fa', 'Farsi'), ('de', 'German'), ('es', 'Spanish'), ('fr', 'French')], default='en', help_text='Select the language of this book', max_length=2),
        ),
    ]
